service: API-CANAL-STARWARS

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
    Resource: "*"

plugins:
  - serverless-offline

functions:
  planetasListar:
    handler: src/api-starwars-gets/App.listarPlanetas
    memorySize: 128
    description: Lista los PLANETAS desde el API STAR WARS
    events:
      - http:
          path: api-canal-starwars/planetas/{id+}
          method: GET

  navesEspacialesListar:
    handler: src/api-starwars-gets/App.listarNavesEspaciales
    memorySize: 128
    description: Lista las NAVES ESPACIALES desde el API STAR WARS
    events:
      - http:
          path: api-canal-starwars/navesEspaciales/{id+}
          method: GET
          
  vehiculosListar:
    handler: src/api-starwars-gets/App.listarVehiculos
    memorySize: 128
    description: Lista los VEHICULOS desde el API STAR WARS
    events:
      - http:
          path: api-canal-starwars/vehiculos/{id+}
          method: GET     
          
  IncursionCrear:
    handler: src/incursion-mnt/App.crearIncursion
    memorySize: 512
    description: Permite crear y persistir los datos de una incursión; Planeta destino, nave(s) espacial(es) y vehiculo(s)
    environment:      
      TABLA_CSW_INCURSION: CSW_INCURSION
    events:
      - http:
          path: api-canal-starwars/incursion/crear
          method: POST

  IncursionListar:
    handler: src/incursion-mnt/App.listarIncursion
    memorySize: 512
    description: Permite obtener todos los datos guardados de una incursión; Planeta destino, nave(s) espacial(es) y vehiculo(s)
    environment:      
      TABLA_CSW_INCURSION: CSW_INCURSION
    events:
      - http:
          path: api-canal-starwars/incursion/listar
          method: GET                    
